fruitwala/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Http;
using fruitwala.Models;
using fruitwala.Data;

namespace fruitwala.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CartController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("cart") == null || HttpContext.Session.GetString("cart")=="")
            {
                ViewBag.available = false;
                return View();
            }
            string[] arr = HttpContext.Session.GetString("cart").Split(',');
            List<Foods> foods = new List<Foods>();

            if (arr.Length > 0 )
            {
                foreach (string item in arr)
                {
                    foods.Add(_context.Foods.Single(b => b.Id == Int32.Parse(item)));
                }
            }
            ViewBag.available = true;
            ViewBag.foods = foods;
            return View();

        }

        public IActionResult GetDetails()
        {
            return View();
        }
        public IActionResult AddCard()
        {
            return View();
        }

        public ActionResult Buy(string id)
        {
            Foods productModel = new Foods();
            if (HttpContext.Session.GetString("cart") == null || HttpContext.Session.GetString("cart") == "")
            {
                HttpContext.Session.SetString("cart", id);
            }
            else
            {
                string str = HttpContext.Session.GetString("cart");
                str = str + "," + id;
                HttpContext.Session.SetString("cart", str);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(string id)
        {
            string[] arr = HttpContext.Session.GetString("cart").Split(',');
            string str = "";
            if (arr.Length > 0)
            {
                arr = arr.Where(val => val != id).ToArray();
            }
            for (int i = 0; i < arr.Length; i++)
            {
                if (i==arr.Length-1)
                {
                    str = str + arr[i];

                }
                else
                    str = str + arr[i] + ",";
            }
            if (str=="")
            {
                HttpContext.Session.SetString("cart", "");
            }
            else
                HttpContext.Session.SetString("cart", str);
            return RedirectToAction("Index");
        }

        //private int isExist(string id)
        //{
        //    List<Item> cart = (List<Item>)Session["cart"];
        //    for (int i = 0; i < cart.Count; i++)
        //        if (cart[i].Product.Id.Equals(id))
        //            return i;
        //    return -1;
        //}
    }
}

fruitwala/Controllers/OrdersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fruitwala.Data;
using fruitwala.Models;
using System.Security.Claims;

namespace fruitwala.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Order.Include(o => o.User);
            return View(await applicationDbContext.ToListAsync());
        }
        public ActionResult CustomOrder()
        {
            if (HttpContext.Session.GetString("cart") != null && HttpContext.Session.GetString("cart") != "")
            {
                ViewBag.usrID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var ID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                ViewBag.User = _context.ApplicationUsers.Single(b => b.Id == ID);
                string[] arr = HttpContext.Session.GetString("cart").Split(',');
                List<Foods> foods = new List<Foods>();

                if (arr.Length > 0)
                {
                    foreach (string item in arr)
                    {
                        foods.Add(_context.Foods.Single(b => b.Id == Int32.Parse(item)));
                    }
                }
                float totalPrice = 0;
                List<OrderDetail> orders = new List<OrderDetail>();

                foreach (var item in foods)
                {
                    orders.Add(new OrderDetail { Quantity = 1, FoodsId = item.Id });
                    totalPrice += item.Price;
                }
                var order = new Order { TotalPrice = totalPrice, Address = ViewBag.User.Address, UserId = ViewBag.User.Id, OrderDetails = orders };
                _context.Order.Add(order);
                _context.SaveChanges();
                HttpContext.Session.SetString("cart", "");
            }

            return RedirectToAction("Index", "Foods");
        }

            // GET: Orders/Details/5
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TotalPrice,Address,UserId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TotalPrice,Address,UserId")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Order.FindAsync(id);
            _context.Order.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.Id == id);
        }
    }
}

fruitwala/Views/Cart/AddCard.cshtml
@{
}
<style>
    .padding {
    padding: 5rem !important;
    margin-left: 300px
}

.card {
    margin-bottom: 1.5rem
}

.card {
    position: relative;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: column;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 1px solid #c8ced3;
    border-radius: .25rem
}

.card-header:first-child {
    border-radius: calc(0.25rem - 1px) calc(0.25rem - 1px) 0 0
}

.card-header {
    padding: .75rem 1.25rem;
    margin-bottom: 0;
    background-color: #f0f3f5;
    border-bottom: 1px solid #c8ced3
}

.card-body {
    flex: 1 1 auto;
    padding: 1.25rem
}

.form-control:focus {
    color: #5c6873;
    background-color: #fff;
    border-color: #c8ced3 !important;
    outline: 0;
    box-shadow: 0 0 0 #F44336
}
</style>
<div class="padding">
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <strong>Credit Card</strong>
                    <small>enter your card details</small>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input class="form-control" id="name" type="text" placeholder="Enter your name">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="ccnumber">Credit Card Number</label>
                                <div class="input-group">
                                    <input class="form-control" type="text" placeholder="0000 0000 0000 0000" autocomplete="email">
                                    <div class="input-group-append">
                                        <span class="input-group-text">
                                            <i class="mdi mdi-credit-card"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="ccmonth">Month</label>
                            <select class="form-control" id="ccmonth">
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                                <option>7</option>
                                <option>8</option>
                                <option>9</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                            </select>
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="ccyear">Year</label>
                            <select class="form-control" id="ccyear">
                                <option>2014</option>
                                <option>2015</option>
                                <option>2016</option>
                                <option>2017</option>
                                <option>2018</option>
                                <option>2019</option>
                                <option>2020</option>
                                <option>2021</option>
                                <option>2022</option>
                                <option>2023</option>
                                <option>2024</option>
                                <option>2025</option>
                            </select>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="cvv">CVV/CVC</label>
                                <input class="form-control" id="cvv" type="text" placeholder="123">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-sm btn-success float-right" type="submit">
                        <i class="mdi mdi-gamepad-circle"></i> Continue</button>
                    <button class="btn btn-sm btn-danger" type="reset">
                        <i class="mdi mdi-lock-reset"></i> Reset</button>
                </div>
            </div>
        </div>
    </div>
</div>

fruitwala/Views/Cart/GetDetails.cshtml
@{
}
<script>
	$('#flexRadioDefault2').click(function(){
		$('#exampleFormControlTextarea1').attr("disabled", false);
	})
	$('#flexRadioDefault1').click(function(){
		$('#exampleFormControlTextarea1').attr("disabled", true);
	})
</script>
<!-- check out section -->
	<div class="checkout-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">
					<div class="form-check">
					  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1"checked>
					  <label class="form-check-label pl-3" for="flexRadioDefault1">
						Ship to Registered Address
					  </label>
					</div>
					<div class="form-check">
					  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
					  <label class="form-check-label pl-3" for="flexRadioDefault2">
						Ship to Different Address
					  </label>
					</div>
					<div class="form-group pt-5">
						<label for="exampleFormControlTextarea1">Shipping Address</label>
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" disabled></textarea>
					  </div>


				</div>

				<div class="col-lg-4">
					<div class="order-details-wrap">
						<table class="order-details">
							<thead>
								<tr>
									<th>Your order Details</th>
									<th>Price</th>
								</tr>
							</thead>
							<tbody class="order-details-body">
								<tr>
									<td>Product</td>
									<td>Total</td>
								</tr>
								<tr>
									<td>Strawberry</td>
									<td>$85.00</td>
								</tr>
								<tr>
									<td>Berry</td>
									<td>$70.00</td>
								</tr>
								<tr>
									<td>Lemon</td>
									<td>$35.00</td>
								</tr>
							</tbody>
							<tbody class="checkout-details">
								<tr>
									<td>Subtotal</td>
									<td>$190</td>
								</tr>
								<tr>
									<td>Shipping</td>
									<td>$50</td>
								</tr>
								<tr>
									<td>Total</td>
									<td>$240</td>
								</tr>
							</tbody>
						</table>
						<a asp-action="AddCard" asp-controller="Cart" class="boxed-btn">Place Order</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end check out section -->

fruitwala/Views/Cart/Index.cshtml
@{
   // Layout = null;
	float total=0;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

	@if (ViewBag.available)
	{
		
	<!-- cart -->
	<div class="cart-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-12">
					<div class="cart-table-wrap">
						<table class="cart-table">
							<thead class="cart-table-head">
								<tr class="table-head-row">
									<th class="product-remove"></th>
									<th class="product-image">Product Image</th>
									<th class="product-name">Name</th>
									<th class="product-price">Price</th>
									<th class="product-total">Total</th>
								</tr>
							</thead>
							<tbody>
								@foreach (Foods item in ViewBag.foods)
								{
									<tr class="table-body-row">
										<td class="product-remove"><a asp-action="Remove" asp-route-id="@item.Id" asp-controller="Cart"><i class="far fa-window-close"></i></a></td>
										<td class="product-image"><img src="~/img/products/product-img-1.jpg" alt=""></td>
										<td class="product-name">@item.Name</td>
										<td class="product-price">$@item.Price</td>
										<td class="product-total">1</td>
									</tr>
									total += item.Price;
								}
							</tbody>
						</table>
					</div>
				</div>

				<div class="col-lg-4">
					<div class="total-section">
						<table class="total-table">
							<thead class="total-table-head">
								<tr class="table-total-row">
									<th>Total</th>
									<th>Price</th>
								</tr>
							</thead>
							<tbody>
								<tr class="total-data">
									<td><strong>Subtotal: </strong></td>
									<td>$@total</td>
								</tr>
								<tr class="total-data">
									<td><strong>Shipping: </strong></td>
									<td>Free</td>
								</tr>
								<tr class="total-data">
									<td><strong>Total: </strong></td>
									<td>$@total</td>
								</tr>
							</tbody>
						</table>
						<div class="cart-buttons">
							<a href="/Foods" class="boxed-btn">Update Cart</a>
							<a asp-action="CustomOrder" asp-controller="Orders" class="boxed-btn black">Check Out</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		</div>
	}
	else
	{
		<div class="alert alert-danger" role="alert">
		  <h4 class="alert-heading">Ops!</h4>
		  <p>Cart is Empty</p>
		  <hr>
		  <p class="mb-0">Please add products then come to cart.</p>
		</div>
	}

</body>
</html>