fruitwala/Controllers/FoodTypesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fruitwala.Data;
using fruitwala.Models;

namespace fruitwala.Controllers
{
    public class FoodTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoodTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: FoodTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.FoodTypes.ToListAsync());
        }

        // GET: FoodTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foodTypes = await _context.FoodTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foodTypes == null)
            {
                return NotFound();
            }

            return View(foodTypes);
        }

        // GET: FoodTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FoodTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FoodType")] FoodTypes foodTypes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(foodTypes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(foodTypes);
        }

        // GET: FoodTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foodTypes = await _context.FoodTypes.FindAsync(id);
            if (foodTypes == null)
            {
                return NotFound();
            }
            return View(foodTypes);
        }

        // POST: FoodTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FoodType")] FoodTypes foodTypes)
        {
            if (id != foodTypes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(foodTypes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodTypesExists(foodTypes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(foodTypes);
        }

        // GET: FoodTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foodTypes = await _context.FoodTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foodTypes == null)
            {
                return NotFound();
            }

            return View(foodTypes);
        }

        // POST: FoodTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var foodTypes = await _context.FoodTypes.FindAsync(id);
            _context.FoodTypes.Remove(foodTypes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodTypesExists(int id)
        {
            return _context.FoodTypes.Any(e => e.Id == id);
        }
    }
}

fruitwala/Controllers/FoodsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fruitwala.Data;
using fruitwala.Models;
using System.Security.Claims;

namespace fruitwala.Controllers
{
    public class FoodsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoodsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public ActionResult Filter(string SearchString)
        {
            if (!String.IsNullOrEmpty(SearchString))
            {
                ViewBag.foods = _context.Foods.Where(b => b.Name!.Contains(SearchString))
                .Include(c => c.FoodTypes);
            }
            return View();
        }

            // GET: Foods
            public async Task<IActionResult> Index()
        {
            var ID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.User = _context.ApplicationUsers.Single(b => b.Id == ID);
            var applicationDbContext = _context.Foods.Include(f => f.FoodTypes);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Foods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foods = await _context.Foods
                .Include(f => f.FoodTypes)
                .FirstOrDefaultAsync(m => m.Id == id);
            ViewBag.comments = _context.Comment.Where(b => b.FoodTypeId == id)
                .Include(c => c.FoodTypes)
                .Include(c => c.User);
            ViewBag.foods = foods; 
            ViewBag.usrID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var ID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.User = _context.ApplicationUsers.Single(b => b.Id == ID);
            if (foods == null)
            {
                return NotFound();
            }
            return View();
        }

        // GET: Foods/Create
        public IActionResult Create()
        {
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType");
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,Image,isAvailable,FoodTypeId")] Foods foods)
        {
            //if (ModelState.IsValid)
            if (true)
            {
                _context.Add(foods);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType", foods.FoodTypeId);
            return View(foods);
        }

        // GET: Foods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foods = await _context.Foods.FindAsync(id);
            if (foods == null)
            {
                return NotFound();
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType", foods.FoodTypeId);
            return View(foods);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,Image,isAvailable,FoodTypeId")] Foods foods)
        {
            if (id != foods.Id)
            {
                return NotFound();
            }

            if (true)
            {
                try
                {
                    _context.Update(foods);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodsExists(foods.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType", foods.FoodTypeId);
            return View(foods);
        }

        // GET: Foods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foods = await _context.Foods
                .Include(f => f.FoodTypes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foods == null)
            {
                return NotFound();
            }

            return View(foods);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var foods = await _context.Foods.FindAsync(id);
            _context.Foods.Remove(foods);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodsExists(int id)
        {
            return _context.Foods.Any(e => e.Id == id);
        }
    }
}

fruitwala/Controllers/HomeController.cs
using fruitwala.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using fruitwala.Data;
namespace fruitwala.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }


        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult AdminDashboard()
        {
            var ID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.User = _context.ApplicationUsers.Single(b => b.Id == ID);
            return View();
        }
         public IActionResult OrderHistory()
        {
            var ID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

            ViewBag.orders = _context.Order.Where(b => b.UserId == ID);

            ViewBag.User = _context.ApplicationUsers.Single(b => b.Id == ID);
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

fruitwala/Controllers/ReviewsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fruitwala.Data;
using fruitwala.Models;

namespace fruitwala.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReviewsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reviews
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Review.Include(r => r.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Reviews/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            ViewData["FoodId"] = new SelectList(_context.Foods, "Id", "Name");

            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,FruitReview,UserId,FoodId,Date")] Review review)
        {
            //if (ModelState.IsValid)
            //{
            //    _context.Add(review);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", review.UserId);
            //return View(review);
            if (true)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", review.UserId);
            ViewData["FoodId"] = new SelectList(_context.Foods, "Id", "Name", review.FoodId);
            return View(review);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", review.UserId);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,FruitReview,UserId,FoodId,Date")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", review.UserId);
            return View(review);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Review.FindAsync(id);
            _context.Review.Remove(review);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
            return _context.Review.Any(e => e.ReviewId == id);
        }
    }
}

fruitwala/Views/Home/AdminDashboard.cshtml
@{
    ViewData["Title"] = "Admin Dashboard";
}
@if (ViewBag.User.isAdmin)
{
<div class="container">
    <div class="row text-center">
        <h1 style="padding-left: 25rem!important;">@ViewData["Title"]</h1>
        <div class="alert alert-success" role="alert">
          <h4 class="alert-heading">Welcome!</h4>
          <p>Our Admin, Fruits are. Add more about the top fruit varieties grown, sold and exported from the United States. While the U.S. grows more than 1000+ fruit varieties,listed have all the imported and local varieties. Each of your effort to add matters.</p>
          <hr>
          <p class="mb-0">No one can reap the fruit before planting the trees. You forget that the fruits belong to all and that the land belongs to no one</p>
        </div>
        <div class="card ml-5" style="width: 18rem;">
          <img class="card-img-top" src="~/img/mf.jpg" alt="mf">
          <div class="card-body">
            <h5 class="card-title">Fruit Category Management</h5>
            <p class="card-text">Create changes in the listed fruit variety available at this online mart.</p>
            <a asp-controller="FoodTypes" asp-action="Index" class="btn btn-primary">MANAGE!</a>
          </div>
        </div>
        <div class="card ml-5" style="width: 18rem;">
          <img class="card-img-top" src="~/img/mft.png" alt="mfts" style="height: 288px;">
          @*~/img/~/img/mft.png   *@
          <div class="card-body">
            <h5 class="card-title">Fruit Variety Management</h5>
            <p class="card-text">Create changes in the listed types of the fruit variety available at this online mart</p>
            <a asp-controller="Foods" asp-action="Index" class="btn btn-primary">MANAGE!</a>
          </div>
        </div>
         <div class="card ml-5" style="width: 18rem;">
          <img class="card-img-top" src="~/img/rw.png" alt="rw">
          <div class="card-body">
            <h5 class="card-title">Food Reviews</h5>
            <p class="card-text">Add your Reviews for the fruit variety available at this online mart.</p>
            <a asp-controller="Reviews" asp-action="Index" class="btn btn-primary">MANAGE!</a>
          </div>
        </div>
    </div>
</div>
}

fruitwala/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!-- hero area -->

<div class="hero-area hero-bg" style="padding: 15%!important; transform: translateY(-159px);">
	<div class="container">
		<div class="row">
			<div class="col-lg-9 offset-lg-2 text-center">
				<div class="hero-text">
					<div class="hero-text-tablecell">
						<p class="subtitle">Fresh & Organic</p>
						<h1>Delicious Seasonal Fruits</h1>
						<div class="hero-btns">
							<a href="/Foods" class="boxed-btn">Fruit Collection</a>
							<a href="contact.html" class="bordered-btn">Contact Us</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container h-100 pt-3">
		<div class="d-flex justify-content-center h-100">
		<div class="searchbar">
			<form asp-controller="Foods" asp-action="Filter">
			@*<input name="search" class="search_input" type="text" placeholder="Search...">
			<a type="submit" class="search_icon"><i class="fas fa-search"></i></a>*@
			<input type="text" name="SearchString" style="height: auto;" />
			<input type="submit" value="Filter" />
			</form>
		</div>
		</div>
	</div>
</div>

<!-- end hero area -->

<!-- features list section -->
<div class="list-section pt-80 pb-80">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
				<div class="list-box d-flex align-items-center">
					<div class="list-icon">
						<i class="fas fa-shipping-fast"></i>
					</div>
					<div class="content">
						<h3>Free Shipping</h3>
						<p>When order over $75</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
				<div class="list-box d-flex align-items-center">
					<div class="list-icon">
						<i class="fas fa-phone-volume"></i>
					</div>
					<div class="content">
						<h3>24/7 Support</h3>
						<p>Get support all day</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6">
				<div class="list-box d-flex justify-content-start align-items-center">
					<div class="list-icon">
						<i class="fas fa-sync"></i>
					</div>
					<div class="content">
						<h3>Refund</h3>
						<p>Get refund within 3 days!</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

	<!-- product section -->
	<div class="product-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">	
						<h3><span class="orange-text">Our</span> Products</h3>
						<p>Quality in a product or service is not what the supplier puts in. it is what the customer gets out and is willing to pay for. A product is not quality because it is hard to make and costs a lot of money, as manufacturers typically believe</p>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="~/img/products/product-img-1.jpg" alt=""></a>
						</div>
						<h3>Strawberry</h3>
						<p class="product-price"><span>Per Kg</span> 85$ </p>
						<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="~/img/products/product-img-2.jpg" alt=""></a>
						</div>
						<h3>Berry</h3>
						<p class="product-price"><span>Per Kg</span> 70$ </p>
						<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 offset-md-3 offset-lg-0 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="~/img/products/product-img-3.jpg" alt=""></a>
						</div>
						<h3>Lemon</h3>
						<p class="product-price"><span>Per Kg</span> 35$ </p>
						<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					</div>
				</div>

				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="~/img/cppapple.jpeg" alt=""></a>
						</div>
						<h3>Apple</h3>
						<p class="product-price"><span>Per Kg</span> 70$ </p>
						<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					</div>
				</div>

			</div>
		</div>
	</div>
	<!-- end product section -->

	<!-- cart banner section -->
	<section class="cart-banner pt-100 pb-100">
    	<div class="container">
        	<div class="row clearfix">
            	<!--Image Column-->
            	<div class="image-column col-lg-6">
                	<div class="image">
                    	<div class="price-box">
                        	<div class="inner-price">
                                <span class="price">
                                    <strong>30%</strong> <br> off per kg
                                </span>
                            </div>
                        </div>
                    	<img src="~/img/a.jpg" alt="">
                    </div>
                </div>
                <!--Content Column-->
                <div class="content-column col-lg-6">
					<h3><span class="orange-text">Deal</span> of the month</h3>
                    <h4>Hikan Strawberry</h4>
                    <div class="text">The garden strawberry (or simply strawberry; Fragaria ananassa)[1] is a widely grown hybrid species of the genus Fragaria, collectively known as the strawberries, which are cultivated worldwide for their fruit. The fruit is widely appreciated for its characteristic aroma, bright red color, juicy texture, and sweetness. It is consumed in large quantities, either fresh or in such prepared foods as jam, juice, pies, ice cream, milkshakes, and chocolates. Artificial strawberry flavorings and aromas are also widely used in products such as candy, soap, lip gloss, perfume, and many others.</div>
                    <!--Countdown Timer-->
                    <div class="time-counter"><div class="time-countdown clearfix" data-countdown="2020/2/01"><div class="counter-column"><div class="inner"><span class="count">00</span>Days</div></div> <div class="counter-column"><div class="inner"><span class="count">00</span>Hours</div></div>  <div class="counter-column"><div class="inner"><span class="count">00</span>Mins</div></div>  <div class="counter-column"><div class="inner"><span class="count">00</span>Secs</div></div></div></div>
                	<a href="cart.html" class="cart-btn mt-3"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
                </div>
            </div>
        </div>
    </section>
    <!-- end cart banner section -->

	<!-- testimonail-section -->
	<div class="testimonail-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 offset-lg-1 text-center">
					<div class="testimonial-sliders">
						<div class="single-testimonial-slider pt-5">
							<div class="client-avater">
								<img src="~/img/avaters/avatar1.png" alt="">
							</div>
							<div class="client-meta">
								<h3>Saira Hakim <span>Local shop owner</span></h3>
								<p class="testimonial-body">
									" To give real service you must add something which cannot be bought or measured with money, and that is sincerity and integrity and we provide you with both. "
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
						<div class="single-testimonial-slider pt-5">
							<div class="client-avater">
								<img src="~/img/avaters/avatar2.png" alt="">
							</div>
							<div class="client-meta">
								<h3>David Niph <span>Local shop owner</span></h3>
								<p class="testimonial-body">
									"Our service shows the world is moved not only by the mighty shoves of the heroes, but also by the aggregate of the tiny pushes of each honest worker."
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
						<div class="single-testimonial-slider pt-5">
							<div class="client-avater">
								<img src="~/img/avaters/avatar3.png" alt="">
							</div>
							<div class="client-meta">
								<h3>Jacob Sikim <span>Local shop owner</span></h3>
								<p class="testimonial-body">
									"A customer is the most important visitor on our premises, he is not dependent on us. We are dependent on him. He is not an interruption in our work. He is the purpose of it. He is not an outsider in our business. He is part of it. We are not doing him a favor by serving him. He is doing us a favor by giving us an opportunity to do so" 
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end testimonail-section -->


	<!-- advertisement section -->
	<div class="abt-section mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<div class="abt-bg">
						<a href="https://www.youtube.com/watch?v=DBLlFWYcIGQ" class="video-play-btn popup-youtube"><i class="fas fa-play"></i></a>
					</div>
				</div>
				<div class="col-lg-6 col-md-12">
					<div class="abt-text">
						<p class="top-sub">Since Year 1999</p>
						<h2>We are <span class="orange-text">Fruitkha</span></h2>
						<p>Are you hungry? Did you have a long and stressful day? Interested in getting a sweet fruit in office or looking to avoid the weekly shop? Then FruitKha Pakistan is the right destination for you! fruitkha offers you a long and detailed list of the best variety of fruits and shops near you to help make your everyday easier. Our online fruit delivery service has it all, whether you fancy Indian, Pakistani or Afghan cuisine.</p>
						<p>Pakistan has over 15,000 fields available in top cities like Islamabad, Lahore, Rawalpindi, and Karachi. Did you know you can order your favourite fruits from fruitkha, too? Check out our inline fruit marts</p></p>
						<a href="about.html" class="boxed-btn mt-4">know more</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end advertisement section -->
	
	<!-- shop banner -->
	<section class="shop-banner">
    	<div class="container">
        	<h3>December sale is on! <br> with big <span class="orange-text">Discount...</span></h3>
            <div class="sale-percent"><span>Sale! <br> Upto</span>50% <span>off</span></div>
            <a href="shop.html" class="cart-btn btn-lg">Shop Now</a>
        </div>
    </section>
	<!-- end shop banner -->

fruitwala/Views/Home/OrderHistory.cshtml
@{
    ViewData["Title"] = "Order History";
}

<div class="row">
	<div class="col-lg-8 offset-lg-2 text-center">
		<div class="section-title">	
			<h3><span class="orange-text">Our</span> Order History</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
		</div>
	</div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Total Price
            </th>
            <th>
                Address
            </th>
            <th>
                Ordered By
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in ViewBag.orders) {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.TotalPrice
            </td>
            <td>
                @item.Address
            </td>
            <td>
                @item.User.FirstName
            </td>
            <td>
            </td>
        </tr>
}
    </tbody>
</table>