fruitwala/Models/FoodTypes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace fruitwala.Models
{
    public class FoodTypes
    {
        public int Id { get; set; }
        [Required]
        [Display (Name ="Food Type")]

        public string FoodType { get; set; }
    }
}

fruitwala/Models/Foods.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace fruitwala.Models
{
    public class Foods
    {
        public int Id { get; set; }
        [Required]

        public string Name { get; set; }
        [Required]

        public string Description { get; set; }
        public float Price { get; set; }
        public string Image { get; set; }

        [Required]
        [Display(Name = "Available")]
        public bool isAvailable { get; set; }

        [Required]
        [Display(Name = "Food Type")]
        public int FoodTypeId  { get; set; }
        [ForeignKey("FoodTypeId")]

        public FoodTypes FoodTypes { get; set; }
    }
}

fruitwala/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Http;
using fruitwala.Models;
using fruitwala.Data;

namespace fruitwala.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CartController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("cart") == null || HttpContext.Session.GetString("cart")=="")
            {
                ViewBag.available = false;
                return View();
            }
            string[] arr = HttpContext.Session.GetString("cart").Split(',');
            List<Foods> foods = new List<Foods>();

            if (arr.Length > 0 )
            {
                foreach (string item in arr)
                {
                    foods.Add(_context.Foods.Single(b => b.Id == Int32.Parse(item)));
                }
            }
            ViewBag.available = true;
            ViewBag.foods = foods;
            return View();

        }

        public IActionResult GetDetails()
        {
            return View();
        }
        public IActionResult AddCard()
        {
            return View();
        }

        public ActionResult Buy(string id)
        {
            Foods productModel = new Foods();
            if (HttpContext.Session.GetString("cart") == null || HttpContext.Session.GetString("cart") == "")
            {
                HttpContext.Session.SetString("cart", id);
            }
            else
            {
                string str = HttpContext.Session.GetString("cart");
                str = str + "," + id;
                HttpContext.Session.SetString("cart", str);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(string id)
        {
            string[] arr = HttpContext.Session.GetString("cart").Split(',');
            string str = "";
            if (arr.Length > 0)
            {
                arr = arr.Where(val => val != id).ToArray();
            }
            for (int i = 0; i < arr.Length; i++)
            {
                if (i==arr.Length-1)
                {
                    str = str + arr[i];

                }
                else
                    str = str + arr[i] + ",";
            }
            if (str=="")
            {
                HttpContext.Session.SetString("cart", "");
            }
            else
                HttpContext.Session.SetString("cart", str);
            return RedirectToAction("Index");
        }

        //private int isExist(string id)
        //{
        //    List<Item> cart = (List<Item>)Session["cart"];
        //    for (int i = 0; i < cart.Count; i++)
        //        if (cart[i].Product.Id.Equals(id))
        //            return i;
        //    return -1;
        //}
    }
}

fruitwala/Controllers/CommentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fruitwala.Data;
using fruitwala.Models;

namespace fruitwala.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CommentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Comment.Include(c => c.FoodTypes).Include(c => c.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment
                .Include(c => c.FoodTypes)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public IActionResult Create()
        {
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType");
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,FoodTypeId,UserId,Date")] Comment comment)
        {
            if (true)
            {
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Foods");
                //return RedirectToAction("Details/" + comment.FoodTypeId, "Foods");
                //return RedirectToAction(nameof(Index));
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType", comment.FoodTypeId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", comment.UserId);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType", comment.FoodTypeId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", comment.UserId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,FoodTypeId,UserId,Date")] Comment comment)
        {
            if (id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType", comment.FoodTypeId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", comment.UserId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment
                .Include(c => c.FoodTypes)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _context.Comment.FindAsync(id);
            _context.Comment.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(int id)
        {
            return _context.Comment.Any(e => e.Id == id);
        }
    }
}

fruitwala/Controllers/FoodsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fruitwala.Data;
using fruitwala.Models;
using System.Security.Claims;

namespace fruitwala.Controllers
{
    public class FoodsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoodsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public ActionResult Filter(string SearchString)
        {
            if (!String.IsNullOrEmpty(SearchString))
            {
                ViewBag.foods = _context.Foods.Where(b => b.Name!.Contains(SearchString))
                .Include(c => c.FoodTypes);
            }
            return View();
        }

            // GET: Foods
            public async Task<IActionResult> Index()
        {
            var ID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.User = _context.ApplicationUsers.Single(b => b.Id == ID);
            var applicationDbContext = _context.Foods.Include(f => f.FoodTypes);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Foods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foods = await _context.Foods
                .Include(f => f.FoodTypes)
                .FirstOrDefaultAsync(m => m.Id == id);
            ViewBag.comments = _context.Comment.Where(b => b.FoodTypeId == id)
                .Include(c => c.FoodTypes)
                .Include(c => c.User);
            ViewBag.foods = foods; 
            ViewBag.usrID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var ID = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.User = _context.ApplicationUsers.Single(b => b.Id == ID);
            if (foods == null)
            {
                return NotFound();
            }
            return View();
        }

        // GET: Foods/Create
        public IActionResult Create()
        {
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType");
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,Image,isAvailable,FoodTypeId")] Foods foods)
        {
            //if (ModelState.IsValid)
            if (true)
            {
                _context.Add(foods);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType", foods.FoodTypeId);
            return View(foods);
        }

        // GET: Foods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foods = await _context.Foods.FindAsync(id);
            if (foods == null)
            {
                return NotFound();
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType", foods.FoodTypeId);
            return View(foods);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,Image,isAvailable,FoodTypeId")] Foods foods)
        {
            if (id != foods.Id)
            {
                return NotFound();
            }

            if (true)
            {
                try
                {
                    _context.Update(foods);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodsExists(foods.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FoodTypeId"] = new SelectList(_context.FoodTypes, "Id", "FoodType", foods.FoodTypeId);
            return View(foods);
        }

        // GET: Foods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foods = await _context.Foods
                .Include(f => f.FoodTypes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foods == null)
            {
                return NotFound();
            }

            return View(foods);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var foods = await _context.Foods.FindAsync(id);
            _context.Foods.Remove(foods);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodsExists(int id)
        {
            return _context.Foods.Any(e => e.Id == id);
        }
    }
}

fruitwala/Views/Foods/Create.cshtml
@model fruitwala.Models.Foods

@{
    //Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Create</title>
</head>
<body>

<h4>Foods</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" type="number" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isAvailable" /> @Html.DisplayNameFor(model => model.isAvailable)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="FoodTypeId" class="control-label"></label>
                <select asp-for="FoodTypeId" class ="form-control" asp-items="ViewBag.FoodTypeId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

fruitwala/Views/Foods/Delete.cshtml
@model fruitwala.Models.Foods

@{
    //Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Foods</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isAvailable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FoodTypes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FoodTypes.FoodType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

fruitwala/Views/Foods/Details.cshtml
@model fruitwala.Models.Comment
@using fruitwala;
@{
   //Layout = "~/Views/Shared/_adminLayout.cshtml";
   ViewData["Title"] = "Product Detail";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Details</title>
</head>
<body>

    @if (ViewBag.User.isAdmin)
    {
        <div>
            <h4>Foods</h4>
            <hr />
            <dl class="row">
                <dt class = "col-sm-2">
                    Name
                </dt>
                <dd class = "col-sm-10">
                    @ViewBag.foods.Name
                </dd>
                <dt class = "col-sm-2">
                    Description
                </dt>
                <dd class = "col-sm-10">
                    @ViewBag.foods.Description
                </dd>
                <dt class = "col-sm-2">
                    Price
                </dt>
                <dd class = "col-sm-10">
                    @ViewBag.foods.Price
                </dd>
                <dt class = "col-sm-2">
                    Image
                </dt>
                <dd class = "col-sm-10">
                    @ViewBag.foods.Image
                </dd>
                <dt class = "col-sm-2">
                    isAvailable
                </dt>
                <dd class = "col-sm-10">
                    @ViewBag.foods.isAvailable
                </dd>
                <dt class = "col-sm-2">
                    Food Type
                </dt>
                <dd class = "col-sm-10">
                    @ViewBag.foods.FoodTypes.FoodType
                </dd>
            </dl>
        </div>
        <div>
            <a asp-action="Edit" asp-route-id="@ViewBag.foods.Id">Edit</a> |
            <a asp-action="Index">Back to List</a>
        </div>
    }
    <!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>See more Details</p>
						<h1>Single Product</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->
<!-- single product -->
	<div class="single-product mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-md-5">
					<div class="single-product-img">
						<img src="~/img/products/product-img-5.jpg" alt="">
					</div>
				</div>
				<div class="col-md-7">
					<div class="single-product-content">
						<h3> @ViewBag.foods.Name </h3>
						<p class="single-product-pricing"><span>Per Kg</span> $@ViewBag.foods.Price </p>
						<p> @ViewBag.foods.Description .</p>
						<div class="single-product-form">
							<form action="index.html">
								<input type="number" placeholder="0">
							</form>
                            @if (ViewBag.foods.isAvailable)
                            {
							    <a asp-action="Buy" asp-route-id="@ViewBag.foods.Id" asp-controller="Cart" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
                            }
                            else
                            {
							    <a href="/" class="cart-btn"><i class="fas fa-shopping-cart"></i> Ops! Out of stock</a>
                            }

							<p><strong>Categories: </strong> @ViewBag.foods.FoodTypes.FoodType </p>
						</div>
						<h4>Share:</h4>
						<ul class="product-share">
							<li><a href=""><i class="fab fa-facebook-f"></i></a></li>
							<li><a href=""><i class="fab fa-twitter"></i></a></li>
							<li><a href=""><i class="fab fa-google-plus-g"></i></a></li>
							<li><a href=""><i class="fab fa-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end single product -->
     @foreach (Comment comment in ViewBag.comments)
     {
        <div class="container mt-5">
        <div class="d-flex justify-content-center row">
            <div class="col-md-8">
                <div class="d-flex flex-column comment-section">
                    <div class="bg-white p-2">
                        <div class="d-flex flex-row user-info"><img class="rounded-circle" src="https://i.imgur.com/RpzrMR2.jpg" width="40">
                            <div class="d-flex flex-column justify-content-start ml-2"><span class="d-block font-weight-bold name">@comment.User.FirstName</span><span class="date text-black-50">Shared publicly - @comment.Date</span></div>
                        </div>
                        <div class="mt-2">
                            <p class="comment-text">@comment.Description</p>
                        </div>
                    </div>
                @if(ViewBag.User.isAdmin)
                {
                    <a class="btn btn-danger" asp-action="Delete" asp-controller="Comments" asp-route-id="@comment.Id">DELETE</a>
                }
                </div>
            </div>
        </div>
        </div>
     }
<div class="bg-light p-2">
    <form asp-controller="Comments" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="d-flex flex-row align-items-start"><img class="rounded-circle" src="https://i.imgur.com/RpzrMR2.jpg" width="40"><textarea asp-for="Description"  class="form-control ml-1 shadow-none textarea"></textarea></div>
        <div class="mt-2 text-right"><button class="btn btn-primary btn-sm shadow-none" type="submit" value="Create">Post comment</button></div>
        <input asp-for="FoodTypeId" value="@ViewBag.foods.Id" class="d-none" />
        <input asp-for="UserId" value="@ViewBag.usrID" class="d-none" />
        <input asp-for="Date" value="@DateTime.Now" class="d-none" />
    </form>
</div>

</body>
</html>

fruitwala/Views/Foods/Filter.cshtml
@{
   // Layout = "~/Views/Shared/_adminLayout.cshtml";
   ViewData["Title"] = "Products";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<!-- product section -->
	<div class="product-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">	
						<h3><span class="orange-text">Our</span> Products</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
					</div>
				</div>
			</div>

			<div class="row">
                @foreach (var item in ViewBag.foods) {
				    <div class="col-lg-4 col-md-6 text-center">
					    <div class="single-product-item">
						    <div class="product-image">
							    <a asp-action="Details" asp-route-id="@item.Id"><img src="~/img/products/product-img-1.jpg" alt=""></a>
						    </div>
						    <h3> @item.Name | @item.FoodTypes.FoodType </h3>
						    <p class="product-price"><span>Per Kg</span> $@item.Price </p>
						    <a asp-action="Buy" asp-route-id="@item.Id" asp-controller="Cart" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					    </div>
				    </div>
                }
			</div>
		</div>
	</div>
	<!-- end product section -->

</body>
</html>

fruitwala/Views/Foods/Index.cshtml
@model IEnumerable<fruitwala.Models.Foods>

@{
   // Layout = "~/Views/Shared/_adminLayout.cshtml";
   ViewData["Title"] = "Products";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
@if (ViewBag.User.isAdmin)
{
    
<p>
    <a class="btn btn-success" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isAvailable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FoodTypes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isAvailable)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FoodTypes.FoodType)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

}

<!-- product section -->
	<div class="product-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">	
						<h3><span class="orange-text">Our</span> Products</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
					</div>
				</div>
			</div>

			<div class="row">
                @foreach (var item in Model) {
				    <div class="col-lg-4 col-md-6 text-center">
					    <div class="single-product-item">
						    <div class="product-image">
							    <a asp-action="Details" asp-route-id="@item.Id"><img src="~/img/products/product-img-1.jpg" alt=""></a>
						    </div>
						    <h3> @Html.DisplayFor(modelItem => item.Name) | @Html.DisplayFor(modelItem => item.FoodTypes.FoodType) </h3>
						    <p class="product-price"><span>Per Kg</span> @Html.DisplayFor(modelItem => item.Price)$ </p>
						    <a asp-action="Buy" asp-route-id="@item.Id" asp-controller="Cart" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					    </div>
				    </div>
                }
			</div>
		</div>
	</div>
	<!-- end product section -->

</body>
</html>